### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by cgahr** [mrnossiom/lspelling#1]
What's the status of this project?

I found this in https://github.com/helix-editor/helix/issues/11660, and I'd love to have a treesitter aware lsp-based spellchecker.

I tried building the project but the nix-shell does not work..

**Comment by mrnossiom** [comment]
Thanks for checking out the project.

I just updated to the latest versions.
Tell me if you have further issues.

I could update the project to use `spellbook` as a spellchecking backend.

**Comment by cgahr** [comment]
Thanks a lot!

`nix shell` and `nix build` are still both failing with
```
       … in the condition of the assert statement
         at /nix/store/rfq6hpk4a4ki1q1856qpb846admnwq5d-source/lib/customisation.nix:365:17:
          364|     in commonAttrs // {
          365|       drvPath = assert condition; drv.drvPath;
             |                 ^
          366|       outPath = assert condition; drv.outPath;

       … while evaluating a branch condition
         at /nix/store/rfq6hpk4a4ki1q1856qpb846admnwq5d-source/pkgs/stdenv/generic/check-meta.nix:504:6:
          503|       inherit (validity) valid;
          504|   in if validity ? handled then validity else validity // {
             |      ^
          505|       # Throw an error if trying to evaluate a non-valid derivation

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: attribute 'package' missing
       at /nix/store/c3x214d514qj09yniiyx4ipfjq1y9wmw-source/package.nix:23:14:
           22|   meta = {
           23|     inherit (cargoTOML.package) description homepage license;
             |              ^
           24|     maintainers = cargoTOML.package.authors;
```

**Comment by mrnossiom** [comment]
Ok, my bad, I should edit the flake to disable shell/build for now.
You can access the right `cargo` version with `nix develop` then build with cargo build.
I've added instructions in README. Tell me if it's not clear enough.

**Comment by cgahr** [comment]
Ah, I see. 

`nix develop` and `cargo build` works, and correctly builds the binary. Spelling mistakes are correctly detect, so that works, thanks!

Some questions and remarks:
- where can I specify the dictionary?
- adding words to the dictionary does not seem to work
- is there a way to spell check only certain treesitter objects, i.e. `text`?

Thanks a lot already for this, I think this has a lot of potential!

**Comment by mrnossiom** [comment]
- You can change the only active dictionary by setting the `HUNSPELL_DICT` env var (https://github.com/mrnossiom/lspelling/blob/main/flake.nix#L65)
- I didn't implement adding custom words yet in ruspell (my lib that implements spellchecking)
- I've added a bit more doc to the README about the internals. You can find the rust query [here](https://github.com/mrnossiom/lspelling/blob/main/lspelling-wordc/queries/rust.scm)

**Comment by cgahr** [comment]
I see, thanks a lot!
